version: '3'
services:
    frontend-build:
        build: ./frontend-build
        volumes:
            - static-web:/mnt/www-out
    redis:
        image: 'redis:3.2'
        command: redis-server
        volumes:
          - 'redis:/data'
        ports:
          - '6379:6379'
    backend:
        build:
            context: ./
        depends_on:
            - frontend-build
        expose:
            - "80"
        ports:
            - "80:80"
        volumes:
            - /usr/local/tamsat-data:/usr/local/tamsat-data
            - static-web:/app/static
    celeryworker:
        build:
            context: ./
            dockerfile: Dockerfile.celeryworker
        depends_on:
            - redis
        stop_grace_period: 2h
        volumes:
            - /usr/local/tamsat-data:/usr/local/tamsat-data
volumes:
    redis:
    static-web:
        driver: local
