FROM python:3.6

RUN pip install --upgrade pip
RUN pip install celery==4.2.0 redis==2.10.6 netcdf4 xarray matplotlib scipy seaborn dask statsmodels pandas toolz

# Indicate to Celery that we are running as root
ENV C_FORCE_ROOT=1

COPY ./app /app
WORKDIR /app

ENV PYTHONPATH=/app

# Start a single celery worker running 2 simultaneous jobs
CMD ["/usr/local/bin/celery", "worker", "-A", "tasks", "-l", "info", "-c", "2", "-B"]
